name: parkpro_admin
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  cupertino_icons: ^1.0.6
  firebase_core: 2.15.1
  firebase_auth: 4.9.0
  cloud_firestore: 4.9.1
  url_launcher: ^6.1.12
  intl: ^0.18.1
  js: ^0.6.7
  crypto: ^3.0.3
  fl_chart: ^0.63.0
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/adminscreenbg.jpeg
    - assets/enforcer.JPG
    - assets/user.JPG
    - assets/motor_area.JPG
    - assets/vehicle_area.JPG
    - assets/loginlogo.png
