// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0YQh3jgSTr80QIYAxDR5BAP0bciJHOU0',
    appId: '1:195524152382:web:2174f239c3d0405224556f',
    messagingSenderId: '195524152382',
    projectId: 'parkpro-6e35e',
    authDomain: 'parkpro-6e35e.firebaseapp.com',
    storageBucket: 'parkpro-6e35e.firebasestorage.app',
    measurementId: 'G-BQD4H1LQLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApDDGHXgZwa1HFnaMerO9erh2iYkUp4QA',
    appId: '1:195524152382:android:232869b1f72e66c824556f',
    messagingSenderId: '195524152382',
    projectId: 'parkpro-6e35e',
    storageBucket: 'parkpro-6e35e.firebasestorage.app',
  );
}
