// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase app on the web.
class DefaultFirebaseOptions {
  /// Firebase configuration for the web platform.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0YQh3jgSTr80QIYAxDR5BAP0bciJHOU0',
    appId: '1:195524152382:web:2174f239c3d0405224556f',
    messagingSenderId: '195524152382',
    projectId: 'parkpro-6e35e',
    authDomain: 'parkpro-6e35e.firebaseapp.com',
    storageBucket: 'parkpro-6e35e.firebasestorage.app',
  );
}
